# Generated by Django 4.1.13 on 2024-03-06 15:15

import cycles.models
from django.db import migrations, models
import django_enumfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPeriod',
            fields=[
                ('user_id_hash', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False)),
                ('current_period_record_id', models.UUIDField(blank=True, null=True)),
                ('last_period_record_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'current_period',
            },
        ),
        migrations.CreateModel(
            name='PeriodRecord',
            fields=[
                ('period_record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id_hash', models.CharField(max_length=200)),
                ('current_status', django_enumfield.db.fields.EnumField(default=1, enum=cycles.models.PeriodRecord.CurrentStatus)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'period_record',
            },
        ),
        migrations.CreateModel(
            name='SymptomsRecord',
            fields=[
                ('symptom_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id_hash', models.CharField(max_length=200)),
                ('symptom', models.CharField(max_length=200)),
                ('comments', models.TextField()),
                ('symptom_occurence', django_enumfield.db.fields.EnumField(enum=cycles.models.SymptomsRecord.SymptomOccurence)),
                ('period_record_id', models.UUIDField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'symptoms_record',
            },
        ),
    ]
