# Generated by Django 4.1.13 on 2024-03-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentperiod',
            name='current_period_record_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='currentperiod',
            name='last_period_record_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='symptomsrecord',
            name='period_record_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
