# Generated by Django 4.1.13 on 2025-03-18 03:10

import cycles.models
from django.db import migrations, models
import django_enumfield.db.fields
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_alter_currentperiod_current_period_record_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseDetails',
            fields=[
                ('detail_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', django_enumfield.db.fields.EnumField(enum=cycles.models.Phases)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('benefits_during_phase', models.TextField()),
                ('difficulty', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('modifications', models.TextField()),
            ],
            options={
                'db_table': 'exercise_details',
            },
        ),
        migrations.CreateModel(
            name='HealthWarning',
            fields=[
                ('warning_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', django_enumfield.db.fields.EnumField(enum=cycles.models.Phases)),
                ('when_to_seek_help', djongo.models.fields.JSONField()),
            ],
            options={
                'db_table': 'health_warning',
            },
        ),
        migrations.CreateModel(
            name='LifestyleAdjustment',
            fields=[
                ('adjustment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', django_enumfield.db.fields.EnumField(enum=cycles.models.Phases)),
                ('work', djongo.models.fields.JSONField()),
                ('social', djongo.models.fields.JSONField()),
                ('relationships', djongo.models.fields.JSONField()),
            ],
            options={
                'db_table': 'lifestyle_adjustment',
            },
        ),
        migrations.CreateModel(
            name='NutrientDetails',
            fields=[
                ('detail_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_nutrient', djongo.models.fields.ArrayField(model_container=cycles.models.NutrientDetailsKeyNutrient)),
                ('meal_plan', djongo.models.fields.JSONField()),
                ('hydration_tips', models.TextField()),
                ('supplement_recommendations', djongo.models.fields.JSONField()),
            ],
            options={
                'db_table': 'nutrient_details',
            },
        ),
        migrations.CreateModel(
            name='PhaseInfo',
            fields=[
                ('phase_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase_type', django_enumfield.db.fields.EnumField(enum=cycles.models.Phases)),
                ('name', models.CharField(max_length=100)),
                ('days_in_cycle', models.CharField(max_length=200)),
                ('hormone_changes', models.TextField()),
                ('common_symptoms', djongo.models.fields.JSONField()),
                ('description', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cycle_phase',
            },
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('recommendation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nutrition', djongo.models.fields.ArrayField(model_container=cycles.models.RecommendationsNutrition)),
                ('exercise', djongo.models.fields.ArrayField(model_container=cycles.models.RecommendationsExercise)),
                ('self_care', djongo.models.fields.ArrayField(model_container=cycles.models.RecommendationsSelfCare)),
            ],
            options={
                'db_table': 'recommendations',
            },
        ),
    ]
