# Generated by Django 4.1.13 on 2025-03-18 05:15

import cycles.models
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0003_exercisedetails_healthwarning_lifestyleadjustment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrientdetails',
            name='key_nutrient',
        ),
        migrations.RemoveField(
            model_name='recommendations',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='recommendations',
            name='nutrition',
        ),
        migrations.RemoveField(
            model_name='recommendations',
            name='self_care',
        ),
        migrations.AddField(
            model_name='nutrientdetails',
            name='phase',
            field=django_enumfield.db.fields.EnumField(default=3, enum=cycles.models.Phases),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendations',
            name='phase',
            field=django_enumfield.db.fields.EnumField(default=3, enum=cycles.models.Phases),
            preserve_default=False,
        ),
    ]
