# Generated by Django 4.1.13 on 2025-03-18 05:17

import cycles.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0004_remove_nutrientdetails_key_nutrient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrientdetails',
            name='key_nutrient',
            field=djongo.models.fields.JSONField(default=list, validators=[cycles.models.validate_key_nutrient]),
        ),
        migrations.AddField(
            model_name='recommendations',
            name='exercise',
            field=djongo.models.fields.JSONField(default=list, validators=[cycles.models.validate_exercise]),
        ),
        migrations.AddField(
            model_name='recommendations',
            name='nutrition',
            field=djongo.models.fields.JSONField(default=list, validators=[cycles.models.validate_nutrition]),
        ),
        migrations.AddField(
            model_name='recommendations',
            name='self_care',
            field=djongo.models.fields.JSONField(default=list, validators=[cycles.models.validate_self_care]),
        ),
    ]
