# Generated by Django 4.1.13 on 2025-03-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0005_nutrientdetails_key_nutrient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodrecord',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
