version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    volumes:
      - static_volume:/app/static
    expose:
      - "8000"
    env_file:
      - .env
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro  # For SSL certificates if using Let's Encrypt
    ports:
      - "80:80"
      - "443:443"  # For HTTPS
    depends_on:
      - web
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

networks:
  app-network:
    driver: bridge

volumes:
  static_volume: