services:
  web:
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"  
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    environment:
      - DJANGO_SETTINGS_MODULE=period_tracking_BE.settings.local
      - MONGODB_URL=mongodb://mongodb:27017/
      - MONGODB_USERNAME=
      - MONGODB_PASSWORD=
    depends_on:
      mongodb:
        condition: service_healthy 


  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo '' --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  mongodb_data: