services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn period_tracking_BE.wsgi:application --bind 0.0.0.0:8000"  
    volumes:
      - .:/app
      - static_volume:/app/static
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy 
    networks:
      - app-network
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/
      - MONGODB_USERNAME=
      - MONGODB_PASSWORD=

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: echo '' --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
  static_volume: 