# Generated by Django 4.1.13 on 2024-03-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSessions',
            fields=[
                ('user_id_hash', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'active_sessions',
            },
        ),
    ]
