# Generated by Django 4.1.13 on 2024-03-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesessions',
            name='session_id',
            field=models.CharField(max_length=1000),
        ),
    ]
