# Generated by Django 4.1.13 on 2024-09-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_activesessions_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerNonRegisteredUserRequests',
            fields=[
                ('ip_address', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tracker_non_registered_user_requests',
            },
        ),
        migrations.CreateModel(
            name='TrackerRegisteredUserRequests',
            fields=[
                ('user_id_hash', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('freq_count', models.IntegerField(default=0)),
                ('freq_req_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tracker_registered_user_requests',
            },
        ),
    ]
