# Generated by Django 4.1.13 on 2025-03-12 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_trackernonregistereduserrequests_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveSessions',
        ),
        migrations.DeleteModel(
            name='TrackerNonRegisteredUserRequests',
        ),
        migrations.DeleteModel(
            name='TrackerRegisteredUserRequests',
        ),
    ]
